config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
# 会員用device
# URL /members/sign_in ...
devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#ゲストユーザーログイン
devise_scope :member do
  post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
end

# 管理者用device
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



# 管理者側ルーティング

namespace :admin do
root to: 'homes#top'
# get "search" => "searches#search", as: 'search'
resources :members, only: [:index,:show,:edit,:update] do
   get 'recipe_index' => 'members#recipe_index'
end
resources :categories, except: [:new, :show]
resources :posts, only: [:index, :show, :edit, :update]
resources :recipes, only: [:index, :show, :edit, :update]
end


# 会員側ルーティング

scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    
 resources :categories, only:[:show]

 resources :members do
     resource :relationships, only:[:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
     get 'myrecipe' => 'members#myrecipe', as: 'myrecipe'
     get 'myalbum' => 'members#myalbum', as: 'myalbum'
     collection do
        get 'member_search'
     end
     member do
        get :bookmarks #特定のidが必要なため、memberメソッド使用
    end
end


# 退会確認画面、論理削除用のルーティング
 get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
 patch '/members/:id/withdraw' => 'members#withdraw', as: 'withdraw'

 resources :recipes do
   resources :recipe_favorites, only: [:create, :destroy]
   resources :comments, only:[:create, :destroy]
   resources :bookmarks, only:[:create, :destroy]
   get :recipe_search, on: :collection
  end


  end


 end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true
  validates :name, length: {in:2..20}
  validates :introduction, length: {maximum:50}

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :recipe_favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :bookmarks, dependent: :destroy
  # has_many :bookmarked_recipes, through: :bookmarks, source: :recipe

  has_one_attached :profile_image

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name = "guestuser"
    end
  end

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_profile_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.member_search(member_search)
    if member_search != ""
      Member.where('name LIKE(?)', "%#{member_search}%")
    else
      Member.all
    end
  end

  #フォローする
  def follow(member)
    relationships.create(followed_id: member.id)
  end

  #フォロー外す
  def unfollow(member)
    relationships.find_by(followed_id: member.id).destroy
  end

  def following?(member)
    followings.include?(member)
  end

  # is_deletedがfalseならtrueを返すようにしている、
  #退会したら再度ログインできないようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end


  #お気に入り（ブックマーク）テーブルにrecipe_idが存在しているか確認
  def bookmarked_by?(recipe_id)
    bookmarks.where(recipe_id: recipe_id).exists?
  end

  #いいねテーブルにrecipe_idが存在しているか確認
  def favorited_by?(recipe_id)
    recipe_favorites.where(recipe_id: recipe_id).exists?
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @member = Member.find(params[:id])
  end

  def index
    @members = Member.page(params[:page])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      flash[:notice] = "#{@member.name}さんの会員情報を更新しました"
       redirect_to admin_member_path(@member.id)
    else
       render :edit
    end
  end

  def recipe_index
    @member = Member.find(params[:member_id])
    @recipes = @member.recipes.order("created_at DESC").page(params[:page]).per(10)
  end

  private
 def member_params
    params.require(:member).permit(:name, :email, :is_deleted)
 end

end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  def guest_sign_in
      member = Member.guest
      sign_in member
      redirect_to member_path(member), notice: 'guestuserでログインしました。'
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/_member_edit.html.erb
<div>
  <label for="inputImage">ProfileImage</label>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
</div>
<div>
  <label for="inputName">Name</label>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"ユーザーネーム"%>
</div>
<div>
  <label for="inputIntroduction">Introduction</label>
    <%= f.text_area :introduction,  autofocus: true, id:"inputName", placeholder:"自己紹介"%>
</div>
<%= f.submit "変更を保存" %>

app/views/admin/members/edit.html.erb
<div class="form">
  <div class="form-title">
    <%= @member.name %>さんの会員情報編集
  </div>

  <%= form_with model: @member, url: admin_member_path(@member.id), method: :patch do |f| %>
  <div class="field">
    会員ID：<strong><%= @member.id %></strong>
  </div>
  <div class="field">
    <%= render "member_edit", f: f %>
  </div>
  <div class="field">
    <%= f.label :会員ステータス %>
    <%= f.radio_button :is_deleted, false %>
    <%= f.label :is_deleted, "有効" %>
    <%= f.radio_button :is_deleted, true %>
    <%= f.label :is_deleted, "退会" %>
  </div>

  <div class="field">
    <%= f.submit "変更を保存", class:"btn btn-outline-secondary btn-lg" %>
  </div>
  <% end %>
</div>

app/views/admin/members/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h2>会員一覧</h2>
    </div>
  </div>
    <div class="row justify-content-center">
      <div class="col-11">
        <table class="table table-bordered table-hover text-center">
          <thead>
            <tr>
              <th style="width: 10%">会員ID</th>
              <th style="width: 30%">氏名</th>
              <th style="width: 30%">メールアドレス</th>
              <th style="width: 30%">会員ステータス</th>
            </tr>
          </thead>
          <tbody>
          <% @members.each do |member| %>
            <tr onclick='window.location="<%= '/admin/members/' + member.id.to_s %>"' role="link">
              <td><%= member.id %></td>
              <td>
              <%= link_to member.name, admin_member_path(member.id), class: "text-dark" %>
              </td>
              <td><%= member.email %></td>
              <td>
                <% if member.active_for_authentication? %>
                  <b class="text-success">有効</b>
                <% else %>
                  <b class="text-muted">退会</b>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
   <div><%= link_to "管理メニュー画面に戻る", admin_root_path, class: "btn btn-secondary text-white" %></div>

    <div class="d-flex justify-content-center">
        <%= paginate @members %>
    </div>
</div>

app/views/admin/members/recipe_index.html.erb
<h3><%= @member.name %>さんのレシピ投稿一覧</h3>
  <%= render "public/recipes/index", recipes: @recipes %>

app/views/admin/members/show.html.erb
<div class="container">
  <div class="row">
    <div>
      <%= @member.name %>さんの会員詳細
    </div>
  </div>
  <div class="row">
    <div class="col-8 ml-5">
      <table class="table table-bordered ml-5">
        <tbody>
          <tr>
            <th class="col-4 text-center">会員ID</th>
            <td><%= @member.id %></td>
          </tr>
          <tr>
            <th class="col-4 text-center">ユーザーネーム</th>
            <td>
              <%= @member.name %>
            </td>
          </tr>
          <tr>
            <th class="col-4 text-center">メールアドレス</th>
            <td><%= @member.email %></td>
          </tr>
          <tr>
            <th class="col-4 text-center">会員ステータス</th>
            <td>
              <% if @member.active_for_authentication? %>
                <b class="text_success">有効</b>
              <% else %>
                <b class="text-muted">退会</b>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div class="mt-4 mb-4 text-center">
      <%= link_to "編集する", edit_admin_member_path(params[:id]), class: "btn btn-success mr-3 text-white" %>　｜
      <%= link_to "#{@member.name}さんのレシピ投稿一覧を見る", admin_member_recipe_index_path(@member), class: "btn btn-info text-white" %>
      </div>
      <div>
        <%= link_to '会員一覧に戻る', admin_members_path, class: "btn btn-secondary text-white" %>
      </div>
    </div>
  </div>
</div>