config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
# 会員用device
# URL /members/sign_in ...
devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#ゲストユーザーログイン
devise_scope :member do
  post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
end

# 管理者用device
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



# 管理者側ルーティング

namespace :admin do
root to: 'homes#top'
# get "search" => "searches#search", as: 'search'
resources :members, only: [:index,:show,:edit,:update] do
   get 'recipe_index' => 'members#recipe_index'
end
resources :categories, except: [:new, :show]
resources :posts, only: [:index, :show, :edit, :update]
resources :recipes, only: [:index, :show, :edit, :update]
end


# 会員側ルーティング

scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    
 resources :categories, only:[:show]

 resources :members do
     resource :relationships, only:[:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
     get 'myrecipe' => 'members#myrecipe', as: 'myrecipe'
     get 'myalbum' => 'members#myalbum', as: 'myalbum'
     collection do
        get 'member_search'
     end
     member do
        get :bookmarks #特定のidが必要なため、memberメソッド使用
    end
end


# 退会確認画面、論理削除用のルーティング
 get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
 patch '/members/:id/withdraw' => 'members#withdraw', as: 'withdraw'

 resources :recipes do
   resources :recipe_favorites, only: [:create, :destroy]
   resources :comments, only:[:create, :destroy]
   resources :bookmarks, only:[:create, :destroy]
   get :recipe_search, on: :collection
  end


  end


 end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :index]

  def index
  @category = Category.new
  @categories = Category.all
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end

  def create
  @category = Category.new(category_params)
  @category.save
  redirect_to admin_categories_path
  end

  def edit
  @category = Category.find(params[:id])
  end

  def update
  @category = Category.find(params[:id])
  @category.update(category_params)
  redirect_to admin_categories_path
  end

  def destroy
  category = Category.find(params[:id])
  category.delete
  redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container py-3">
 <div class="row">
  <h3>カテゴリー編集</h3>
 </div>

 <div class="row pt-4">
   <%= form_with model: @category, url: admin_category_path(@category.id), method: :patch do |f| %>
   <%= f.label :カテゴリー名 %>
   <%= f.text_field :name %>
   <%= f.submit "変更を保存" ,class: "btn btn-primary" %>
   <%= link_to "削除する", admin_category_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger" %>
   <% end %>
 </div>
 <div>
  <%= link_to "カテゴリー一覧に戻る", admin_categories_path %>
 </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
 <div class="row">
  <h3>カテゴリー管理画面</h3>
 </div>
  <div>
   <%= form_with model: @category, url: admin_categories_path, method: :post do |f| %>
   <%= f.label :新規カテゴリー名を入力 %>
   <%= f.text_field :name %>
   <%= f.submit "新規登録", class: "btn btn-success ml-3 mb-2" %>
   <% end %>
  </div>
  <div class="row">
   <div class="col-5">
    <table class="table table-bordered table-hover text-center">
     <thead class="thead">
      <tr>
       <th>カテゴリー一覧</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody class="tbody">
       <% @categories.each do |all_category| %>
        <tr>
         <td><%= all_category.name %></td>
         <td><%= link_to "編集する", edit_admin_category_path(all_category.id), class: "btn btn-sm btn-success admin_category_edit text-white" %></td>
        </tr>
       <% end %>
     </tbody>
    </table>
   </div>
  </div>
   <div><%= link_to "管理メニュー画面に戻る", admin_root_path, class: "btn btn-secondary text-white" %></div>
</div>