config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
# 会員用device
# URL /members/sign_in ...
devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#ゲストユーザーログイン
devise_scope :member do
  post 'members/guest_sign_in', to: 'members/sessions#guest_sign_in'
end

# 管理者用device
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



# 管理者側ルーティング

namespace :admin do
root to: 'homes#top'
# get "search" => "searches#search", as: 'search'
resources :members, only: [:index,:show,:edit,:update] do
   get 'recipe_index' => 'members#recipe_index'
end
resources :categories, except: [:new, :show]
resources :posts, only: [:index, :show, :edit, :update]
resources :recipes, only: [:index, :show, :edit, :update]
end


# 会員側ルーティング

scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    
 resources :categories, only:[:show]

 resources :members do
     resource :relationships, only:[:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
     get 'myrecipe' => 'members#myrecipe', as: 'myrecipe'
     get 'myalbum' => 'members#myalbum', as: 'myalbum'
     collection do
        get 'member_search'
     end
     member do
        get :bookmarks #特定のidが必要なため、memberメソッド使用
    end
end


# 退会確認画面、論理削除用のルーティング
 get '/members/:id/unsubscribe' => 'members#unsubscribe', as: 'unsubscribe'
 patch '/members/:id/withdraw' => 'members#withdraw', as: 'withdraw'

 resources :recipes do
   resources :recipe_favorites, only: [:create, :destroy]
   resources :comments, only:[:create, :destroy]
   resources :bookmarks, only:[:create, :destroy]
   get :recipe_search, on: :collection
  end


  end


 end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :member
  belongs_to :recipe

  validates_uniqueness_of :recipe_id, scope: :member_id
  # バリデーション（ユーザーと記事の組み合わせは一意）
  # 同じ投稿を複数回お気に入り登録させないため。
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :recipe

  validates :comment, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true
  validates :name, length: {in:2..20}
  validates :introduction, length: {maximum:50}

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :recipe_favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :bookmarks, dependent: :destroy
  # has_many :bookmarked_recipes, through: :bookmarks, source: :recipe

  has_one_attached :profile_image

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name = "guestuser"
    end
  end

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_profile_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.member_search(member_search)
    if member_search != ""
      Member.where('name LIKE(?)', "%#{member_search}%")
    else
      Member.all
    end
  end

  #フォローする
  def follow(member)
    relationships.create(followed_id: member.id)
  end

  #フォロー外す
  def unfollow(member)
    relationships.find_by(followed_id: member.id).destroy
  end

  def following?(member)
    followings.include?(member)
  end

  # is_deletedがfalseならtrueを返すようにしている、
  #退会したら再度ログインできないようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end


  #お気に入り（ブックマーク）テーブルにrecipe_idが存在しているか確認
  def bookmarked_by?(recipe_id)
    bookmarks.where(recipe_id: recipe_id).exists?
  end

  #いいねテーブルにrecipe_idが存在しているか確認
  def favorited_by?(recipe_id)
    recipe_favorites.where(recipe_id: recipe_id).exists?
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  validates :title, presence: true
  validates :ingredient, presence: true
  validates :body, presence: true, length: {maximum:250}

  belongs_to :member
  has_many :comments, dependent: :destroy
  has_many :recipe_favorites, dependent: :destroy
  belongs_to :category
  has_many :bookmarks, dependent: :destroy
  has_many :tags, dependent: :destroy

  has_one_attached :recipe_image

  def recipe_favorited_by?(member)
    recipe_favorites.exists?(member_id: member.id)
  end

  def get_recipe_image(width, height)
    unless recipe_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      recipe_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
    recipe_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.recipe_search(recipe_search)
    if recipe_search != ""
      Recipe.where(['title LIKE(?) OR ingredient LIKE(?) OR body LIKE(?)', "%#{recipe_search}%", "%#{recipe_search}%", "%#{recipe_search}%"])
    else
      Recipe.all
    end
  end


end

app/models/recipe_favorite.rb
class RecipeFavorite < ApplicationRecord
  belongs_to :member
  belongs_to :recipe
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Member"
  belongs_to :followed, class_name: "Member"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :recipe
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @member = Member.find(params[:id])
  end

  def index
    @members = Member.page(params[:page])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      flash[:notice] = "#{@member.name}さんの会員情報を更新しました"
       redirect_to admin_member_path(@member.id)
    else
       render :edit
    end
  end

  def recipe_index
    @member = Member.find(params[:member_id])
    @recipes = @member.recipes.order("created_at DESC").page(params[:page]).per(10)
  end

  private
 def member_params
    params.require(:member).permit(:name, :email, :is_deleted)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <h5><%= obj.errors.count %>件のエラー</h5>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <div class="col-12">
    ©2022 cookmemo
  </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><h1 class="text-center">cook memo</h1></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <% if member_signed_in? %>
        <ul class="navbar-nav">
           <li class="nav-item">
              <%= link_to "マイページ", member_path(current_member.id), class:'nav-link  text-muted' %>
            </li>
            <li class="nav-item">
              <%= link_to "レシピを見る", recipes_path, class:'nav-link  text-muted' %>
            </li>
            <li class="nav-item">
              <%= link_to "ユーザー一覧", members_path, class:'nav-link  text-muted' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class:'nav-link  text-muted' %>
            </li>
          </ul>
      <% elsif admin_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
          <%= link_to "管理メニュー", admin_root_path, class:'nav-link  text-muted' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:'nav-link  text-muted' %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "About", about_path, class:'nav-link  text-muted' %>
          </li>
          <li class="nav-item">
            <%= link_to "レシピを見る", recipes_path, class:'nav-link  text-muted' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ゲストログイン', members_guest_sign_in_path, class:'nav-link  text-muted', method: :post %>
          </li>
          <li class="nav-item"><%= link_to '会員登録', new_member_registration_path, class: 'nav-link  text-muted' %>
          </li>
          <li class="nav-item"><%= link_to 'ログイン', new_member_session_path, class: 'nav-link text-muted' %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
<div class="notice">
 <%= notice %>
</div>
<% elsif alert %>
  <div class="notice">
 <%= alert %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookmemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat&family=Montserrat:ital,wght@0,200;1,400&family=Roboto:ital,wght@1,100&family=Sacramento&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Shippori+Mincho&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main class="container">
      <% if member_signed_in? || admin_signed_in? %>
        <div class="d-flex justify-content-center mb-2">
          <%= render 'public/searches/form' %>
        </div>
      <% end %>
      <div id="flash-message">
        <%= render "layouts/notice" %>
      </div>
      <%= yield %>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>

    <script src="https://kit.fontawesome.com/ce2f52ecc1.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>